const Constants = {
  MEMBER: {
    SUPER_ADMIN: "Super Admin",
  },
  ADMIN_ROLES: {
    SECTIONS: {
      TEST: "test", // update sections list
    },
    PERMISSIONS: {
      CREATE: "CREATE",
      READ: "READ",
      UPDATE: "UPDATE",
      DELETE: "DELETE",
      LIST: "LIST",
    },
  },
  ROLE_ATTRIBUTES: {
    DASHBOARD: "dashboard",
    DYNAMICFORM: "dynamicForm",
    INPUTCATEGORY: "inputCategory",
    MEDIA: "Media",
    FOOTER: "footer",
    EVENT: "event",
    HEADERADD: "headerAdd",
    HEADER: "header",
    PAGE: "page",
    POST: "post",
    FORM: "form",
    SERVICE: "service",
    ANNOUNCEMENT: "announcement",
    PRESSRELEASE: "pressRelease",
    SEODATA: "seodata",
    NEWSLETTERSUBSCRIPTION: "newsletter-subscription",
    USER: "user",
    ADMIN: "Admin",
    HOMEPAGE: "Homepage",
    USERS: "users",
    BLOGS: "blogs",
    WORKSHOPS: "workshops",
    WEBINARS: "Webinars",
    COURSES: "Courses",
    CARRER: "Career",
    CASESTUDIES: "casestudies",
    ROLEMANAGEMENT: "rolemanagement",
    NOTIFICATION: "notifications",
    CATEGORY: "category",
    CONTACT: "contact",
    MERCHANT: "merchant",
    CATEGORYTAGS: "categorytags",
    WHITEPAPERS: "whitepapers",
    NEWSLETTER: "newsletter",
    ABOUT: "about",
    REQUESTPROPOSAL: "RequestProposal",
  },
  ROLE_ACCESS_TYPES: {
    CREATE: "create",
    READ: "read",
    UPDATE: "update",
    DELETE: "delete",
    DETAIL: "details",
  },
};

export default Constants;
