const ABOUT_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_TURACOZ_TEAM_BEGIN: "GET_TURACOZ_TEAM_BEGIN",
  GET_TURACOZ_TEAM_SUCCESS: "GET_TURACOZ_TEAM_SUCCESS",
  GET_TURACOZ_TEAM_FAILURE: "GET_TURACOZ_TEAM_FAILURE",

  POST_TURACOZ_TEAM_BEGIN: "POST_TURACOZ_TEAM_BEGIN",
  POST_TURACOZ_TEAM_SUCCESS: "POST_TURACOZ_TEAM_SUCCESS",
  POST_TURACOZ_TEAM_FAILURE: "POST_TURACOZ_TEAM_FAILURE",

  UPDATE_TURACOZ_TEAM_BEGIN: "UPDATE_TURACOZ_TEAM_BEGIN",
  UPDATE_TURACOZ_TEAM_SUCCESS: "UPDATE_TURACOZ_TEAM_SUCCESS",
  UPDATE_TURACOZ_TEAM_FAILURE: "UPDATE_TURACOZ_TEAM_FAILURE",

  POST_TURACOZ_TEAM_IMAGE_BEGIN: "POST_TURACOZ_TEAM_IMAGE_BEGIN",
  POST_TURACOZ_TEAM_IMAGE_SUCCESS: "POST_TURACOZ_TEAM_IMAGE_SUCCESS",
  POST_TURACOZ_TEAM_IMAGE_FAILURE: "POST_TURACOZ_TEAM_IMAGE_FAILURE",

  DELETE_TURACOZ_TEAM_BEGIN: "DELETE_TURACOZ_TEAM_BEGIN",
  DELETE_TURACOZ_TEAM_SUCCESS: "DELETE_TURACOZ_TEAM_SUCCESS",
  DELETE_TURACOZ_TEAM_FAILURE: "DELETE_TURACOZ_TEAM_FAILURE",

  GET_LIFE_AT_TURACOZ_TEAM_BEGIN: "GET_LIFE_AT_TURACOZ_TEAM_BEGIN",
  GET_LIFE_AT_TURACOZ_TEAM_SUCCESS: "GET_LIFE_AT_TURACOZ_TEAM_SUCCESS",
  GET_LIFE_AT_TURACOZ_TEAM_FAILURE: "GET_LIFE_AT_TURACOZ_TEAM_FAILURE",

  POST_LIFE_AT_TURACOZ_TEAM_BEGIN: "POST_LIFE_AT_TURACOZ_TEAM_BEGIN",
  POST_LIFE_AT_TURACOZ_TEAM_SUCCESS: "POST_LIFE_AT_TURACOZ_TEAM_SUCCESS",
  POST_LIFE_AT_TURACOZ_TEAM_FAILURE: "POST_LIFE_AT_TURACOZ_TEAM_FAILURE",

  UPDATE_LIFE_AT_TURACOZ_TEAM_BEGIN: "UPDATE_LIFE_AT_TURACOZ_TEAM_BEGIN",
  UPDATE_LIFE_AT_TURACOZ_TEAM_SUCCESS: "UPDATE_LIFE_AT_TURACOZ_TEAM_SUCCESS",
  UPDATE_LIFE_AT_TURACOZ_TEAM_FAILURE: "UPDATE_LIFE_AT_TURACOZ_TEAM_FAILURE",

  POST_LIFE_AT_TURACOZ_TEAM_IMAGE_BEGIN:
    "POST_LIFE_AT_TURACOZ_TEAM_IMAGE_BEGIN",
  POST_LIFE_AT_TURACOZ_TEAM_IMAGE_SUCCESS:
    "POST_LIFE_AT_TURACOZ_TEAM_IMAGE_SUCCESS",
  POST_LIFE_AT_TURACOZ_TEAM_IMAGE_FAILURE:
    "POST_LIFE_AT_TURACOZ_TEAM_IMAGE_FAILURE",

  DELETE_LIFE_AT_TURACOZ_TEAM_BEGIN: "DELETE_LIFE_AT_TURACOZ_TEAM_BEGIN",
  DELETE_LIFE_AT_TURACOZ_TEAM_SUCCESS: "DELETE_LIFE_AT_TURACOZ_TEAM_SUCCESS",
  DELETE_LIFE_AT_TURACOZ_TEAM_FAILURE: "DELETE_LIFE_AT_TURACOZ_TEAM_FAILURE",

  GET_IMAGE_SLIDER_ABOUT_BEGIN: "GET_IMAGE_SLIDER_ABOUT_BEGIN",
  GET_IMAGE_SLIDER_ABOUT_SUCCESS: "GET_IMAGE_SLIDER_ABOUT_SUCCESS",
  GET_IMAGE_SLIDER_ABOUT_FAILURE: "GET_IMAGE_SLIDER_ABOUT_FAILURE",

  POST_IMAGE_SLIDER_ABOUT_BEGIN: "POST_IMAGE_SLIDER_ABOUT_BEGIN",
  POST_IMAGE_SLIDER_ABOUT_SUCCESS: "POST_IMAGE_SLIDER_ABOUT_SUCCESS",
  POST_IMAGE_SLIDER_ABOUT_FAILURE: "POST_IMAGE_SLIDER_ABOUT_FAILURE",
};

export default ABOUT_TYPES;
