const ADMIN_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_LIST_BEGIN: "GET_ADMINLIST_BEGIN",
  GET_LIST_SUCCESS: "GET_ADMINLIST_SUCCESS",
  GET_LIST_FAILURE: "GET_ADMINLIST_FAILURE",

  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",

  POST_ADMIN_BEGIN: "POST_ADMIN_BEGIN",
  POST_ADMIN_SUCCESS: "POST_ADMIN_SUCCESS",
  POST_ADMIN_FAILURE: "POST_ADMIN_FAILURE",

  ADMIN_SUBMITTING: "ADMIN_SUBMITTING",
};

export default ADMIN_TYPES;
