const ANNOUNCEMENT_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ANNOUNCEMENT_LIST_BEGIN: "GET_ANNOUNCEMENT_LIST_BEGIN",
  GET_ANNOUNCEMENT_LIST_SUCCESS: "GET_ANNOUNCEMENT_LIST_SUCCESS",
  GET_ANNOUNCEMENT_LIST_FAILURE: "GET_ANNOUNCEMENT_LIST_FAILURE",

  POST_ANNOUNCEMENT_BEGIN: "POST_ANNOUNCEMENT_BEGIN",
  POST_ANNOUNCEMENT_SUCCESS: "POST_ANNOUNCEMENT_SUCCESS",
  POST_ANNOUNCEMENT_FAILURE: "POST_ANNOUNCEMENT_FAILURE",

  UPDATE_ANNOUNCEMENT_BEGIN: "UPDATE_ANNOUNCEMENT_BEGIN",
  UPDATE_ANNOUNCEMENT_SUCCESS: "UPDATE_ANNOUNCEMENT_SUCCESS",
  UPDATE_ANNOUNCEMENT_FAILURE: "UPDATE_ANNOUNCEMENT_FAILURE",

  POST_IMAGE_ANNOUNCEMENT_BEGIN: "POST_IMAGE_ANNOUNCEMENT_BEGIN",
  POST_IMAGE_ANNOUNCEMENT_SUCCESS: "POST_IMAGE_ANNOUNCEMENT_SUCCESS",
  POST_IMAGE_ANNOUNCEMENT_FAILURE: "POST_IMAGE_ANNOUNCEMENT_FAILURE",

  GET_BYID_ANNOUNCEMENT_BEGIN: "GET_BYID_ANNOUNCEMENT_BEGIN",
  GET_BYID_ANNOUNCEMENT_SUCCESS: "GET_BYID_ANNOUNCEMENT_SUCCESS",
  GET_BYID_ANNOUNCEMENT_FAILURE: "GET_BYID_ANNOUNCEMENT_FAILURE",
};

export default ANNOUNCEMENT_TYPES;
