const AUTH_TYPES = {
  RESET_STATE: "RESET_STATE",

  UPDATE_USER_DATA: "UPDATE_USER_DATA",

  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_NO_2FA_SUCCESS: "LOGIN_NO_2FA_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REFRESH_TOKEN_BEGIN: "REFRESH_TOKEN_BEGIN",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILURE: "REFRESH_TOKEN_FAILURE",

  POST_VERIFY_ACCOUNT_EMAIL_BEGIN: "POST_VERIFY_ACCOUNT_EMAIL_BEGIN",
  POST_VERIFY_ACCOUNT_EMAIL_SUCCESS: "POST_VERIFY_ACCOUNT_EMAIL_SUCCESS",
  POST_VERIFY_ACCOUNT_EMAIL_FAILURE: "POST_VERIFY_ACCOUNT_EMAIL_FAILURE",

  PASSWORD_VERIFY_ACCOUNT_EMAIL_BEGIN: "PASSWORD_VERIFY_ACCOUNT_EMAIL_BEGIN",
  PASSWORD_VERIFY_ACCOUNT_EMAIL_SUCCESS:
    "PASSWORD_VERIFY_ACCOUNT_EMAIL_SUCCESS",
  PASSWORD_VERIFY_ACCOUNT_EMAIL_FAILURE:
    "PASSWORD_VERIFY_ACCOUNT_EMAIL_FAILURE",

  RESET_PASSWORD_BEGIN: "RESET_PASSWORD_BEGIN",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  SET_SUBMITTING: "SET_SUBMITTING",
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",

  LOGOUT: "LOGOUT",

  GET_PROFILE_DETAILS_BEGIN: "GET_PROFILE_DETAILS_BEGIN",
  GET_PROFILE_DETAILS_SUCCESS: "GET_PROFILE_DETAILS_SUCCESS",
  GET_PROFILE_DETAILS_FAILURE: "GET_PROFILE_DETAILS_FAILURE",

  POST_ADD_IMAGE_BEGIN: "POST_ADD_IMAGE_BEGIN",
  POST_ADD_IMAGE_SUCCESS: "POST_ADD_IMAGE_SUCCESS",
  POST_ADD_IMAGE_FAILURE: "POST_ADD_IMAGE_FAILURE",

  POST_PROFILE_BEGIN: "POST_PROFILE_BEGIN",
  POST_PROFILE_SUCCESS: "POST_PROFILE_SUCCESS",
  POST_PROFILE_FAILURE: "POST_PROFILE_FAILURE",

  GET_ADMIN_BEGIN: "GET_ADMIN_BEGIN",
  GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
  GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",
};

export default AUTH_TYPES;
