const BLOG_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_LIST_BEGIN: "GET_BLOG_LIST_BEGIN",
  GET_LIST_SUCCESS: "GET_BLOG_LIST_SUCCESS",
  GET_LIST_FAILURE: "GET_BLOG_LIST_FAILURE",

  POST_BLOG_BEGIN: "POST_BLOG_BEGIN",
  POST_BLOG_SUCCESS: "POST_BLOG_SUCCESS",
  POST_BLOG_FAILURE: "POST_BLOG_FAILURE",

  UPDATE_BLOG_BEGIN: "UPDATE_BLOG_BEGIN",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",

  POST_IMAGE_BLOG_BEGIN: "POST_IMAGE_BLOG_BEGIN",
  POST_IMAGE_BLOG_SUCCESS: "POST_IMAGE_BLOG_SUCCESS",
  POST_IMAGE_BLOG_FAILURE: "POST_IMAGE_BLOG_FAILURE",

};

export default BLOG_TYPES;
