const CARRER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_CARRER_LIST_BEGIN: "GET_CARRER_LIST_BEGIN",
  GET_CARRER_LIST_SUCCESS: "GET_CARRER_LIST_SUCCESS",
  GET_CARRER_LIST_FAILURE: "GET_CARRER_LIST_FAILURE",

  POST_CARRER_BEGIN: "POST_CARRER_BEGIN",
  POST_CARRER_SUCCESS: "POST_CARRER_SUCCESS",
  POST_CARRER_FAILURE: "POST_CARRER_FAILURE",

  UPDATE_CARRER_BEGIN: "UPDATE_CARRER_BEGIN",
  UPDATE_CARRER_SUCCESS: "UPDATE_CARRER_SUCCESS",
  UPDATE_CARRER_FAILURE: "UPDATE_CARRER_FAILURE",

  POST_IMAGE_CARRER_BEGIN: "POST_IMAGE_CARRER_BEGIN",
  POST_IMAGE_CARRER_SUCCESS: "POST_IMAGE_CARRER_SUCCESS",
  POST_IMAGE_CARRER_FAILURE: "POST_IMAGE_CARRER_FAILURE",

  GET_BYID_CARRER_BEGIN: "GET_BYID_CARRER_BEGIN",
  GET_BYID_CARRER_SUCCESS: "GET_BYID_CARRER_SUCCESS",
  GET_BYID_CARRER_FAILURE: "GET_BYID_CARRER_FAILURE",
};

export default CARRER_TYPES;
