const CASESTUDIES_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_CASESTUDIES_LIST_BEGIN: "GET_CASESTUDIES_LIST_BEGIN",
  GET_CASESTUDIES_LIST_SUCCESS: "GET_CASESTUDIES_LIST_SUCCESS",
  GET_CASESTUDIES_LIST_FAILURE: "GET_CASESTUDIES_LIST_FAILURE",

  POST_CASESTUDIES_BEGIN: "POST_CASESTUDIES_BEGIN",
  POST_CASESTUDIES_SUCCESS: "POST_CASESTUDIES_SUCCESS",
  POST_CASESTUDIES_FAILURE: "POST_CASESTUDIES_FAILURE",

  UPDATE_CASESTUDIES_BEGIN: "UPDATE_CASESTUDIES_BEGIN",
  UPDATE_CASESTUDIES_SUCCESS: "UPDATE_CASESTUDIES_SUCCESS",
  UPDATE_CASESTUDIES_FAILURE: "UPDATE_CASESTUDIES_FAILURE",

  POST_IMAGE_CASESTUDIES_BEGIN: "POST_IMAGE_CASESTUDIES_BEGIN",
  POST_IMAGE_CASESTUDIES_SUCCESS: "POST_IMAGE_CASESTUDIES_SUCCESS",
  POST_IMAGE_CASESTUDIES_FAILURE: "POST_IMAGE_CASESTUDIES_FAILURE",

  GET_BYID_CASESTUDIES_BEGIN: "GET_BYID_CASESTUDIES_BEGIN",
  GET_BYID_CASESTUDIES_SUCCESS: "GET_BYID_CASESTUDIES_SUCCESS",
  GET_BYID_CASESTUDIES_FAILURE: "GET_BYID_CASESTUDIES_FAILURE",

};

export default CASESTUDIES_TYPES;
