const CATEGORY_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_CATEGORY_LIST_BEGIN: "GET_CATEGORY_LIST_BEGIN",
  GET_CATEGORY_LIST_SUCCESS: "GET_CATEGORY_LIST_SUCCESS",
  GET_CATEGORY_LIST_FAILURE: "GET_CATEGORY_LIST_FAILURE",

  POST_CATEGORY_BEGIN: "POST_CATEGORY_BEGIN",
  POST_CATEGORY_SUCCESS: "POST_CATEGORY_SUCCESS",
  POST_CATEGORY_FAILURE: "POST_CATEGORY_FAILURE",

  UPDATE_CATEGORY_BEGIN: "UPDATE_CATEGORY_BEGIN",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

  DELETE_CATEGORY_BEGIN: "DELETE_CATEGORY_BEGIN",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
};

export default CATEGORY_TYPES;
