const CONTACT_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_CONTACT_LIST_BEGIN: "GET_CONTACT_LIST_BEGIN",
  GET_CONTACT_LIST_SUCCESS: "GET_CONTACT_LIST_SUCCESS",
  GET_CONTACT_LIST_FAILURE: "GET_CONTACT_LIST_FAILURE",

  DELETE_CONTACT_BEGIN: "DELETE_CONTACT_BEGIN",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",
};

export default CONTACT_TYPES;
