const COURSE_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ALL_COURSE_LIST_BEGIN: "GET_ALL_COURSE_LIST_BEGIN",
  GET_ALL_COURSE_LIST_SUCCESS: "GET_ALL_COURSE_LIST_SUCCESS",
  GET_ALL_COURSE_LIST_FAILURE: "GET_ALL_COURSE_LIST_FAILURE",

  POST_IMAGE_COURSE_LIST_BEGIN: "POST_IMAGE_COURSE_LIST_BEGIN",
  POST_IMAGE_COURSE_LIST_SUCCESS: "POST_IMAGE_COURSE_LIST_SUCCESS",
  POST_IMAGE_COURSE_LIST_FAILURE: "POST_IMAGE_COURSE_LIST_FAILURE",

  DELETE_COURSE_LIST_BEGIN: "DELETE_COURSE_LIST_BEGIN",
  DELETE_COURSE_LIST_SUCCESS: "DELETE_COURSE_LIST_SUCCESS",
  DELETE_COURSE_LIST_FAILURE: "DELETE_COURSE_LIST_FAILURE",

  UPDATE_COURSE_LIST_BEGIN: "UPDATE_COURSE_LIST_BEGIN",
  UPDATE_COURSE_LIST_SUCCESS: "UPDATE_COURSE_LIST_SUCCESS",
  UPDATE_COURSE_LIST_FAILURE: "UPDATE_COURSE_LIST_FAILURE",
};

export default COURSE_TYPES;
