const DASHBOARD_TYPES = {
  GET_DASHBOARD_DETAILS_BEGIN: "GET_DASHBOARD_DETAILS_BEGIN",
  GET_DASHBOARD_DETAILS_SUCCESS: "GET_DASHBOARD_DETAILS_SUCCESS",
  GET_DASHBOARD_DETAILS_FAILURE: "GET_DASHBOARD_DETAILS_FAILURE",

  RESET_STATE: "RESET_STATE",
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
};

export default DASHBOARD_TYPES;
