const DYNAMIC_FORM_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_DYNAMIC_FORM_BEGIN: "GET_DYNAMIC_FORM_BEGIN",
    GET_DYNAMIC_FORM_SUCCESS: "GET_DYNAMIC_FORM_SUCCESS",
    GET_DYNAMIC_FORM_FAILURE: "GET_DYNAMIC_FORM_FAILURE",
  
    POST_DYNAMIC_FORM_BEGIN: "POST_DYNAMIC_FORM_BEGIN",
    POST_DYNAMIC_FORM_SUCCESS: "POST_DYNAMIC_FORM_SUCCESS",
    POST_DYNAMIC_FORM_FAILURE: "POST_DYNAMIC_FORM_FAILURE",
  
    UPDATE_DYNAMIC_FORM_BEGIN: "UPDATE_DYNAMIC_FORM_BEGIN",
    UPDATE_DYNAMIC_FORM_SUCCESS: "UPDATE_DYNAMIC_FORM_SUCCESS",
    UPDATE_DYNAMIC_FORM_FAILURE: "UPDATE_DYNAMIC_FORM_FAILURE",
  
    DELETE_DYNAMIC_FORM_BEGIN: "DELETE_DYNAMIC_FORM_BEGIN",
    DELETE_DYNAMIC_FORM_SUCCESS: "DELETE_DYNAMIC_FORM_SUCCESS",
    DELETE_DYNAMIC_FORM_FAILURE: "DELETE_DYNAMIC_FORM_FAILURE",
  };
  
  export default DYNAMIC_FORM_TYPES;
  