const DYNAMIC_REGISTER_FORM_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_DYNAMIC_REGISTER_FORM_BEGIN: "GET_DYNAMIC_REGISTER_FORM_BEGIN",
  GET_DYNAMIC_REGISTER_FORM_SUCCESS: "GET_DYNAMIC_REGISTER_FORM_SUCCESS",
  GET_DYNAMIC_REGISTER_FORM_FAILURE: "GET_DYNAMIC_REGISTER_FORM_FAILURE",

  DELETE_DYNAMIC_REGISTER_FORM_BEGIN: "DELETE_DYNAMIC_REGISTER_FORM_BEGIN",
  DELETE_DYNAMIC_REGISTER_FORM_SUCCESS: "DELETE_DYNAMIC_REGISTER_FORM_SUCCESS",
  DELETE_DYNAMIC_REGISTER_FORM_FAILURE: "DELETE_DYNAMIC_REGISTER_FORM_FAILURE",
};

export default DYNAMIC_REGISTER_FORM_TYPES;
