const EVENT_CONFERENCE_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_EVENT_CONFERENCE_LIST_BEGIN: "GET_EVENT_CONFERENCE_LIST_BEGIN",
  GET_EVENT_CONFERENCE_LIST_SUCCESS: "GET_EVENT_CONFERENCE_LIST_SUCCESS",
  GET_EVENT_CONFERENCE_LIST_FAILURE: "GET_EVENT_CONFERENCE_LIST_FAILURE",

  POST_EVENT_CONFERENCE_BEGIN: "POST_EVENT_CONFERENCE_BEGIN",
  POST_EVENT_CONFERENCE_SUCCESS: "POST_EVENT_CONFERENCE_SUCCESS",
  POST_EVENT_CONFERENCE_FAILURE: "POST_EVENT_CONFERENCE_FAILURE",

  UPDATE_EVENT_CONFERENCE_BEGIN: "UPDATE_EVENT_CONFERENCE_BEGIN",
  UPDATE_EVENT_CONFERENCE_SUCCESS: "UPDATE_EVENT_CONFERENCE_SUCCESS",
  UPDATE_EVENT_CONFERENCE_FAILURE: "UPDATE_EVENT_CONFERENCE_FAILURE",

  POST_IMAGE_EVENT_CONFERENCE_BEGIN: "POST_IMAGE_EVENT_CONFERENCE_BEGIN",
  POST_IMAGE_EVENT_CONFERENCE_SUCCESS: "POST_IMAGE_EVENT_CONFERENCE_SUCCESS",
  POST_IMAGE_EVENT_CONFERENCE_FAILURE: "POST_IMAGE_EVENT_CONFERENCE_FAILURE",

  GET_BYID_EVENT_CONFERENCE_BEGIN: "GET_BYID_EVENT_CONFERENCE_BEGIN",
  GET_BYID_EVENT_CONFERENCE_SUCCESS: "GET_BYID_EVENT_CONFERENCE_SUCCESS",
  GET_BYID_EVENT_CONFERENCE_FAILURE: "GET_BYID_EVENT_CONFERENCE_FAILURE",
};

export default EVENT_CONFERENCE_TYPES;
