const FOOTER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_FOOTER_LIST_BEGIN: "GET_FOOTER_LIST_BEGIN",
  GET_FOOTER_LIST_SUCCESS: "GET_FOOTER_LIST_SUCCESS",
  GET_FOOTER_LIST_FAILURE: "GET_FOOTER_LIST_FAILURE",

  POST_FOOTER_LIST_BEGIN: "POST_FOOTER_LIST_BEGIN",
  POST_FOOTER_LIST_SUCCESS: "POST_FOOTER_LIST_SUCCESS",
  POST_FOOTER_LIST_FAILURE: "POST_FOOTER_LIST_FAILURE",

  UPDATE_FOOTER_LIST_BEGIN: "UPDATE_FOOTER_LIST_BEGIN",
  UPDATE_FOOTER_LIST_SUCCESS: "UPDATE_FOOTER_LIST_SUCCESS",
  UPDATE_FOOTER_LIST_FAILURE: "UPDATE_FOOTER_LIST_FAILURE",

  DELETE_FOOTER_LIST_BEGIN: "DELETE_FOOTER_LIST_BEGIN",
  DELETE_FOOTER_LIST_SUCCESS: "DELETE_FOOTER_LIST_SUCCESS",
  DELETE_FOOTER_LIST_FAILURE: "DELETE_FOOTER_LIST_FAILURE",
};

export default FOOTER_TYPES;
