const HEADER_ADD_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HEADER_ADD_LIST_BEGIN: "GET_HEADER_ADD_LIST_BEGIN",
  GET_HEADER_ADD_LIST_SUCCESS: "GET_HEADER_ADD_LIST_SUCCESS",
  GET_HEADER_ADD_LIST_FAILURE: "GET_HEADER_ADD_LIST_FAILURE",

  POST_HEADER_ADD_BEGIN: "POST_HEADER_ADD_BEGIN",
  POST_HEADER_ADD_SUCCESS: "POST_HEADER_ADD_SUCCESS",
  POST_HEADER_ADD_FAILURE: "POST_HEADER_ADD_FAILURE",

  UPDATE_HEADER_ADD_BEGIN: "UPDATE_HEADER_ADD_BEGIN",
  UPDATE_HEADER_ADD_SUCCESS: "UPDATE_HEADER_ADD_SUCCESS",
  UPDATE_HEADER_ADD_FAILURE: "UPDATE_HEADER_ADD_FAILURE",

  DELETE_HEADER_ADD_BEGIN: "DELETE_HEADER_ADD_BEGIN",
  DELETE_HEADER_ADD_SUCCESS: "DELETE_HEADER_ADD_SUCCESS",
  DELETE_HEADER_ADD_FAILURE: "DELETE_HEADER_ADD_FAILURE",
};

export default HEADER_ADD_TYPES;
