const HEADER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HEADER_BEGIN: "GET_HEADER_BEGIN",
  GET_HEADER_SUCCESS: "GET_HEADER_SUCCESS",
  GET_HEADER_FAILURE: "GET_HEADER_FAILURE",

  POST_HEADER_BEGIN: "POST_HEADER_BEGIN",
  POST_HEADER_SUCCESS: "POST_HEADER_SUCCESS",
  POST_HEADER_FAILURE: "POST_HEADER_FAILURE",

  UPDATE_HEADER_BEGIN: "UPDATE_HEADER_BEGIN",
  UPDATE_HEADER_SUCCESS: "UPDATE_HEADER_SUCCESS",
  UPDATE_HEADER_FAILURE: "UPDATE_HEADER_FAILURE",

  DELETE_HEADER_BEGIN: "DELETE_HEADER_BEGIN",
  DELETE_HEADER_SUCCESS: "DELETE_HEADER_SUCCESS",
  DELETE_HEADER_FAILURE: "DELETE_HEADER_FAILURE",
};

export default HEADER_TYPES;
