const HOMEPAGE_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_HOMEPAGE_LIST_BEGIN: "GET_HOMEPAGE_LIST_BEGIN",
  GET_HOMEPAGE_LIST_SUCCESS: "GET_HOMEPAGE_LIST_SUCCESS",
  GET_HOMEPAGE_LIST_FAILURE: "GET_HOMEPAGE_LIST_FAILURE",

  POST_HOMEPAGE_BEGIN: "POST_HOMEPAGE_BEGIN",
  POST_HOMEPAGE_SUCCESS: "POST_HOMEPAGE_SUCCESS",
  POST_HOMEPAGE_FAILURE: "POST_HOMEPAGE_FAILURE",

  UPDATE_HOMEPAGE_BEGIN: "UPDATE_HOMEPAGE_BEGIN",
  UPDATE_HOMEPAGE_SUCCESS: "UPDATE_HOMEPAGE_SUCCESS",
  UPDATE_HOMEPAGE_FAILURE: "UPDATE_HOMEPAGE_FAILURE",

  DELETE_HOMEPAGE_BEGIN: "DELETE_HOMEPAGE_BEGIN",
  DELETE_HOMEPAGE_SUCCESS: "DELETE_HOMEPAGE_SUCCESS",
  DELETE_HOMEPAGE_FAILURE: "DELETE_HOMEPAGE_FAILURE",

  POST_IMAGE_HOMEPAGE_BEGIN: "POST_IMAGE_HOMEPAGE_BEGIN",
  POST_IMAGE_HOMEPAGE_SUCCESS: "POST_IMAGE_HOMEPAGE_SUCCESS",
  POST_IMAGE_HOMEPAGE_FAILURE: "POST_IMAGE_HOMEPAGE_FAILURE",

  GET_CLIENT_LIST_BEGIN: "GET_CLIENT_LIST_BEGIN",
  GET_CLIENT_LIST_SUCCESS: "GET_CLIENT_LIST_SUCCESS",
  GET_CLIENT_LIST_FAILURE: "GET_CLIENT_LIST_FAILURE",

  POST_CLIENT_BEGIN: "POST_CLIENT_BEGIN",
  POST_CLIENT_SUCCESS: "POST_CLIENT_SUCCESS",
  POST_CLIENT_FAILURE: "POST_CLIENT_FAILURE",

  POST_IMAGE_CLIENT_BEGIN: "POST_IMAGE_CLIENT_BEGIN",
  POST_IMAGE_CLIENT_SUCCESS: "POST_IMAGE_CLIENT_SUCCESS",
  POST_IMAGE_CLIENT_FAILURE: "POST_IMAGE_CLIENT_FAILURE",

  UPDATE_CLIENT_BEGIN: "UPDATE_CLIENT_BEGIN",
  UPDATE_CLIENT_SUCCESS: "UPDATE_CLIENT_SUCCESS",
  UPDATE_CLIENT_FAILURE: "UPDATE_CLIENT_FAILURE",

  DELETE_CLIENT_BEGIN: "DELETE_CLIENT_BEGIN",
  DELETE_CLIENT_SUCCESS: "DELETE_CLIENT_SUCCESS",
  DELETE_CLIENT_FAILURE: "DELETE_CLIENT_FAILURE",
};

export default HOMEPAGE_TYPES;
