const INPUT_CATEGORY_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_INPUT_CATEGORY_LIST_BEGIN: "GET_INPUT_CATEGORY_LIST_BEGIN",
    GET_INPUT_CATEGORY_LIST_SUCCESS: "GET_INPUT_CATEGORY_LIST_SUCCESS",
    GET_INPUT_CATEGORY_LIST_FAILURE: "GET_INPUT_CATEGORY_LIST_FAILURE",
  
    POST_INPUT_CATEGORY_BEGIN: "POST_INPUT_CATEGORY_BEGIN",
    POST_INPUT_CATEGORY_SUCCESS: "POST_INPUT_CATEGORY_SUCCESS",
    POST_INPUT_CATEGORY_FAILURE: "POST_INPUT_CATEGORY_FAILURE",
  
    UPDATE_INPUT_CATEGORY_BEGIN: "UPDATE_INPUT_CATEGORY_BEGIN",
    UPDATE_INPUT_CATEGORY_SUCCESS: "UPDATE_INPUT_CATEGORY_SUCCESS",
    UPDATE_INPUT_CATEGORY_FAILURE: "UPDATE_INPUT_CATEGORY_FAILURE",
  
    DELETE_INPUT_CATEGORY_BEGIN: "DELETE_INPUT_CATEGORY_BEGIN",
    DELETE_INPUT_CATEGORY_SUCCESS: "DELETE_INPUT_CATEGORY_SUCCESS",
    DELETE_INPUT_CATEGORY_FAILURE: "DELETE_INPUT_CATEGORY_FAILURE",
  };
  
  export default INPUT_CATEGORY_TYPES;
  