const MEDIA_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_MEDIA_BEGIN: "GET_MEDIA_BEGIN",
  GET_MEDIA_SUCCESS: "GET_MEDIA_SUCCESS",
  GET_MEDIA_FAILURE: "GET_MEDIA_FAILURE",

  POST_MEDIA_BEGIN: "POST_MEDIA_BEGIN",
  POST_MEDIA_SUCCESS: "POST_MEDIA_SUCCESS",
  POST_MEDIA_FAILURE: "POST_MEDIA_FAILURE",

  DELETE_MEDIA_BEGIN: "DELETE_MEDIA_BEGIN",
  DELETE_MEDIA_SUCCESS: "DELETE_MEDIA_SUCCESS",
  DELETE_MEDIA_FAILURE: "DELETE_MEDIA_FAILURE",
};

export default MEDIA_TYPES;
