const NEWSLETTER_SUBSCRIPTION_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_NEWSLETTER_SUBSCRIPTION_LIST_BEGIN:
    "GET_NEWSLETTER_SUBSCRIPTION_LIST_BEGIN",
  GET_NEWSLETTER_SUBSCRIPTION_LIST_SUCCESS:
    "GET_NEWSLETTER_SUBSCRIPTION_LIST_SUCCESS",
  GET_NEWSLETTER_SUBSCRIPTION_LIST_FAILURE:
    "GET_NEWSLETTER_SUBSCRIPTION_LIST_FAILURE",

  DELETE_NEWSLETTER_SUBSCRIPTION_LIST_BEGIN:
    "DELETE_NEWSLETTER_SUBSCRIPTION_LIST_BEGIN",
  DELETE_NEWSLETTER_SUBSCRIPTION_LIST_SUCCESS:
    "DELETE_NEWSLETTER_SUBSCRIPTION_LIST_SUCCESS",
  DELETE_NEWSLETTER_SUBSCRIPTION_LIST_FAILURE:
    "DELETE_NEWSLETTER_SUBSCRIPTION_LIST_FAILURE",
};

export default NEWSLETTER_SUBSCRIPTION_TYPES;
