const NEWSLETTER_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_NEWSLETTER_LIST_BEGIN: "GET_NEWSLETTER_LIST_BEGIN",
    GET_NEWSLETTER_LIST_SUCCESS: "GET_NEWSLETTER_LIST_SUCCESS",
    GET_NEWSLETTER_LIST_FAILURE: "GET_NEWSLETTER_LIST_FAILURE",
  
    POST_NEWSLETTER_BEGIN: "POST_NEWSLETTER_BEGIN",
    POST_NEWSLETTER_SUCCESS: "POST_NEWSLETTER_SUCCESS",
    POST_NEWSLETTER_FAILURE: "POST_NEWSLETTER_FAILURE",
  
    UPDATE_NEWSLETTER_BEGIN: "UPDATE_NEWSLETTER_BEGIN",
    UPDATE_NEWSLETTER_SUCCESS: "UPDATE_NEWSLETTER_SUCCESS",
    UPDATE_NEWSLETTER_FAILURE: "UPDATE_NEWSLETTER_FAILURE",
  
    POST_IMAGE_NEWSLETTER_BEGIN: "POST_IMAGE_NEWSLETTER_BEGIN",
    POST_IMAGE_NEWSLETTER_SUCCESS: "POST_IMAGE_NEWSLETTER_SUCCESS",
    POST_IMAGE_NEWSLETTER_FAILURE: "POST_IMAGE_NEWSLETTER_FAILURE",
  };
  
  export default NEWSLETTER_TYPES;
  