const PRESS_RELEASE_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_PRESS_RELEASE_LIST_BEGIN: "GET_PRESS_RELEASE_LIST_BEGIN",
  GET_PRESS_RELEASE_LIST_SUCCESS: "GET_PRESS_RELEASE_LIST_SUCCESS",
  GET_PRESS_RELEASE_LIST_FAILURE: "GET_PRESS_RELEASE_LIST_FAILURE",

  POST_PRESS_RELEASE_BEGIN: "POST_PRESS_RELEASE_BEGIN",
  POST_PRESS_RELEASE_SUCCESS: "POST_PRESS_RELEASE_SUCCESS",
  POST_PRESS_RELEASE_FAILURE: "POST_PRESS_RELEASE_FAILURE",

  UPDATE_PRESS_RELEASE_BEGIN: "UPDATE_PRESS_RELEASE_BEGIN",
  UPDATE_PRESS_RELEASE_SUCCESS: "UPDATE_PRESS_RELEASE_SUCCESS",
  UPDATE_PRESS_RELEASE_FAILURE: "UPDATE_PRESS_RELEASE_FAILURE",

  POST_IMAGE_PRESS_RELEASE_BEGIN: "POST_IMAGE_PRESS_RELEASE_BEGIN",
  POST_IMAGE_PRESS_RELEASE_SUCCESS: "POST_IMAGE_PRESS_RELEASE_SUCCESS",
  POST_IMAGE_PRESS_RELEASE_FAILURE: "POST_IMAGE_PRESS_RELEASE_FAILURE",

  GET_BYID_PRESS_RELEASE_BEGIN: "GET_BYID_PRESS_RELEASE_BEGIN",
  GET_BYID_PRESS_RELEASE_SUCCESS: "GET_BYID_PRESS_RELEASE_SUCCESS",
  GET_BYID_PRESS_RELEASE_FAILURE: "GET_BYID_PRESS_RELEASE_FAILURE",
};

export default PRESS_RELEASE_TYPES;
