const REQUEST_PROPOSAL_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_REQUEST_PROPOSAL_LIST_BEGIN: "GET_REQUEST_PROPOSAL_LIST_BEGIN",
    GET_REQUEST_PROPOSAL_LIST_SUCCESS: "GET_REQUEST_PROPOSAL_LIST_SUCCESS",
    GET_REQUEST_PROPOSAL_LIST_FAILURE: "GET_REQUEST_PROPOSAL_LIST_FAILURE",
  
    DELETE_REQUEST_PROPOSAL_BEGIN: "DELETE_REQUEST_PROPOSAL_BEGIN",
    DELETE_REQUEST_PROPOSAL_SUCCESS: "DELETE_REQUEST_PROPOSAL_SUCCESS",
    DELETE_REQUEST_PROPOSAL_FAILURE: "DELETE_REQUEST_PROPOSAL_FAILURE",
  };
  
  export default REQUEST_PROPOSAL_TYPES;
  