const SEO_DATA_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_LIST_BEGIN: "GET_SEO_DATA_LIST_BEGIN",
  GET_LIST_SUCCESS: "GET_SEO_DATA_LIST_SUCCESS",
  GET_LIST_FAILURE: "GET_SEO_DATA_LIST_FAILURE",

  POST_SEO_DATA_BEGIN: "POST_SEO_DATA_BEGIN",
  POST_SEO_DATA_SUCCESS: "POST_SEO_DATA_SUCCESS",
  POST_SEO_DATA_FAILURE: "POST_SEO_DATA_FAILURE",

  UPDATE_SEO_DATA_BEGIN: "UPDATE_SEO_DATA_BEGIN",
  UPDATE_SEO_DATA_SUCCESS: "UPDATE_SEO_DATA_SUCCESS",
  UPDATE_SEO_DATA_FAILURE: "UPDATE_SEO_DATA_FAILURE",
};

export default SEO_DATA_TYPES;
