const SERVICE_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_SERVICE_BEGIN: "GET_SERVICE_BEGIN",
  GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",
  GET_SERVICE_FAILURE: "GET_SERVICE_FAILURE",

  POST_SERVICE_BEGIN: "POST_SERVICE_BEGIN",
  POST_SERVICE_SUCCESS: "POST_SERVICE_SUCCESS",
  POST_SERVICE_FAILURE: "POST_SERVICE_FAILURE",

  UPDATE_SERVICE_BEGIN: "UPDATE_SERVICE_BEGIN",
  UPDATE_SERVICE_SUCCESS: "UPDATE_SERVICE_SUCCESS",
  UPDATE_SERVICE_FAILURE: "UPDATE_SERVICE_FAILURE",

  DELETE_SERVICE_BEGIN: "DELETE_SERVICE_BEGIN",
  DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_FAILURE: "DELETE_SERVICE_FAILURE",
};

export default SERVICE_TYPES;
