const USER_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_USER_LIST_BEGIN: "GET_USER_LIST_BEGIN",
  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_FAILURE: "GET_USER_LIST_FAILURE",

  GET_ADMIN_LIST_BEGIN: "GET_ADMIN_LIST_BEGIN",
  GET_ADMIN_LIST_SUCCESS: "GET_ADMIN_LIST_SUCCESS",
  GET_ADMIN_LIST_FAILURE: "GET_ADMIN_LIST_FAILURE",

  GET_USER_DETAILS_BEGIN: "GET_USER_DETAILS_BEGIN",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",

  UPDATE_USER_BEGIN: "UPDATE_USER_BEGIN",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  CREATE_USER_BEGIN: "CREATE_USER_BEGIN",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  DELETE_USER_BEGIN: "DELETE_USER_BEGIN",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
};

export default USER_TYPES;
