const WEBINAR_CONFERENCE_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_WEBINAR_CONFERENCE_LIST_BEGIN: "GET_WEBINAR_CONFERENCE_LIST_BEGIN",
    GET_WEBINAR_CONFERENCE_LIST_SUCCESS: "GET_WEBINAR_CONFERENCE_LIST_SUCCESS",
    GET_WEBINAR_CONFERENCE_LIST_FAILURE: "GET_WEBINAR_CONFERENCE_LIST_FAILURE",
  
    POST_WEBINAR_CONFERENCE_BEGIN: "POST_WEBINAR_CONFERENCE_BEGIN",
    POST_WEBINAR_CONFERENCE_SUCCESS: "POST_WEBINAR_CONFERENCE_SUCCESS",
    POST_WEBINAR_CONFERENCE_FAILURE: "POST_WEBINAR_CONFERENCE_FAILURE",
  
    UPDATE_WEBINAR_CONFERENCE_BEGIN: "UPDATE_WEBINAR_CONFERENCE_BEGIN",
    UPDATE_WEBINAR_CONFERENCE_SUCCESS: "UPDATE_WEBINAR_CONFERENCE_SUCCESS",
    UPDATE_WEBINAR_CONFERENCE_FAILURE: "UPDATE_WEBINAR_CONFERENCE_FAILURE",
  
    POST_IMAGE_WEBINAR_CONFERENCE_BEGIN: "POST_IMAGE_WEBINAR_CONFERENCE_BEGIN",
    POST_IMAGE_WEBINAR_CONFERENCE_SUCCESS: "POST_IMAGE_WEBINAR_CONFERENCE_SUCCESS",
    POST_IMAGE_WEBINAR_CONFERENCE_FAILURE: "POST_IMAGE_WEBINAR_CONFERENCE_FAILURE",
  
    GET_BYID_WEBINAR_CONFERENCE_BEGIN: "GET_BYID_WEBINAR_CONFERENCE_BEGIN",
    GET_BYID_WEBINAR_CONFERENCE_SUCCESS: "GET_BYID_WEBINAR_CONFERENCE_SUCCESS",
    GET_BYID_WEBINAR_CONFERENCE_FAILURE: "GET_BYID_WEBINAR_CONFERENCE_FAILURE",
  };
  
  export default WEBINAR_CONFERENCE_TYPES;
  