const WEBINAR_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_ALL_WEBINAR_LIST_BEGIN: "GET_ALL_WEBINAR_LIST_BEGIN",
    GET_ALL_WEBINAR_LIST_SUCCESS: "GET_ALL_WEBINAR_LIST_SUCCESS",
    GET_ALL_WEBINAR_LIST_FAILURE: "GET_ALL_WEBINAR_LIST_FAILURE",
  
    POST_IMAGE_WEBINAR_LIST_BEGIN: "POST_IMAGE_WEBINAR_LIST_BEGIN",
    POST_IMAGE_WEBINAR_LIST_SUCCESS: "POST_IMAGE_WEBINAR_LIST_SUCCESS",
    POST_IMAGE_WEBINAR_LIST_FAILURE: "POST_IMAGE_WEBINAR_LIST_FAILURE",
  
    DELETE_WEBINAR_LIST_BEGIN: "DELETE_WEBINAR_LIST_BEGIN",
    DELETE_WEBINAR_LIST_SUCCESS: "DELETE_WEBINAR_LIST_SUCCESS",
    DELETE_WEBINAR_LIST_FAILURE: "DELETE_WEBINAR_LIST_FAILURE",
  
    UPDATE_WEBINAR_LIST_BEGIN: "UPDATE_WEBINAR_LIST_BEGIN",
    UPDATE_WEBINAR_LIST_SUCCESS: "UPDATE_WEBINAR_LIST_SUCCESS",
    UPDATE_WEBINAR_LIST_FAILURE: "UPDATE_WEBINAR_LIST_FAILURE",
  };
  
  export default WEBINAR_TYPES;
  