const WHITEPAPER_TYPES = {
    RESET_STATE: "RESET_STATE",
  
    GET_WHITEPAPER_LIST_BEGIN: "GET_WHITEPAPER_LIST_BEGIN",
    GET_WHITEPAPER_LIST_SUCCESS: "GET_WHITEPAPER_LIST_SUCCESS",
    GET_WHITEPAPER_LIST_FAILURE: "GET_WHITEPAPER_LIST_FAILURE",
  
    POST_WHITEPAPER_BEGIN: "POST_WHITEPAPER_BEGIN",
    POST_WHITEPAPER_SUCCESS: "POST_WHITEPAPER_SUCCESS",
    POST_WHITEPAPER_FAILURE: "POST_WHITEPAPER_FAILURE",
  
    UPDATE_WHITEPAPER_BEGIN: "UPDATE_WHITEPAPER_BEGIN",
    UPDATE_WHITEPAPER_SUCCESS: "UPDATE_WHITEPAPER_SUCCESS",
    UPDATE_WHITEPAPER_FAILURE: "UPDATE_WHITEPAPER_FAILURE",
  
    POST_IMAGE_WHITEPAPER_BEGIN: "POST_IMAGE_WHITEPAPER_BEGIN",
    POST_IMAGE_WHITEPAPER_SUCCESS: "POST_IMAGE_WHITEPAPER_SUCCESS",
    POST_IMAGE_WHITEPAPER_FAILURE: "POST_IMAGE_WHITEPAPER_FAILURE",
  };
  
  export default WHITEPAPER_TYPES;
  