const WORKSHOP_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ALL_WORKSHOP_LIST_BEGIN: "GET_ALL_WORKSHOP_LIST_BEGIN",
  GET_ALL_WORKSHOP_LIST_SUCCESS: "GET_ALL_WORKSHOP_LIST_SUCCESS",
  GET_ALL_WORKSHOP_LIST_FAILURE: "GET_ALL_WORKSHOP_LIST_FAILURE",

  POST_WORKSHOP_LIST_BEGIN: "POST_WORKSHOP_LIST_BEGIN",
  POST_WORKSHOP_LIST_SUCCESS: "POST_WORKSHOP_LIST_SUCCESS",
  POST_WORKSHOP_LIST_FAILURE: "POST_WORKSHOP_LIST_FAILURE",

  DELETE_WORKSHOP_LIST_BEGIN: "DELETE_WORKSHOP_LIST_BEGIN",
  DELETE_WORKSHOP_LIST_SUCCESS: "DELETE_WORKSHOP_LIST_SUCCESS",
  DELETE_WORKSHOP_LIST_FAILURE: "DELETE_WORKSHOP_LIST_FAILURE",

  UPDATE_WORKSHOP_LIST_BEGIN: "UPDATE_WORKSHOP_LIST_BEGIN",
  UPDATE_WORKSHOP_LIST_SUCCESS: "UPDATE_WORKSHOP_LIST_SUCCESS",
  UPDATE_WORKSHOP_LIST_FAILURE: "UPDATE_WORKSHOP_LIST_FAILURE",
};

export default WORKSHOP_TYPES;
